"use client";

export async function callClaude(
  prompt: string,
  system?: string
): Promise<string> {
  const res = await fetch("/api/generate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prompt, system }),
  });

  const data = await res.json();

  if (!res.ok || data.error) {
    throw new Error(data.error || `API error ${res.status}`);
  }

  return data.text || "";
}

export function exportPDF(
  title: string,
  sections: { heading: string; body: string }[]
) {
  const content = sections
    .map(
      (s) =>
        `<h2 style="color:#d97706;margin-top:24px;font-size:14px;text-transform:uppercase;letter-spacing:2px;">${s.heading}</h2><div style="white-space:pre-wrap;font-size:13px;line-height:1.7;color:#1f2937;">${s.body}</div>`
    )
    .join(
      "<hr style='border:none;border-top:1px solid #e5e7eb;margin:16px 0'/>"
    );
  const html = `<html><head><title>${title}</title><style>body{font-family:Georgia,serif;max-width:800px;margin:40px auto;padding:0 40px;}h1{font-size:22px;color:#111;}p{color:#666;font-size:12px;}</style></head><body><h1>${title}</h1><p>Generated by Woww GM · ${new Date().toLocaleDateString()}</p><hr/>${content}</body></html>`;
  const w = window.open("", "_blank");
  if (w) {
    w.document.write(html);
    w.document.close();
    w.print();
  }
}
